### ISSUE TITLE
Commit messages are not informational

### ISSUE THREAD

**Issue by alois9866** [cmc-haskell-2018/straminata#34]
We need to change our commit messages style to something like:

> Done something (_in commit title_)
>
> Issues #N, M, ... (_in commit comment_)

**Comment by fizruk** [comment]
See [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/).

**Comment by alois9866** [comment]
Commit message should be:

> _Commit subject_
> 
> Commit body – some in depth explanation of the changes, optional.
>
> `Issue #`_issue-number_

Commit title should be a proper sentence, no more that ~50 symbols, with first word capitalized but without a full stop at the end.
__And:__
A properly formed Git commit subject line should always be able to complete the following sentence:
"If applied, this commit will your subject line here"
