### ISSUE TITLE
Refactor CommonTypes.hs

### ISSUE THREAD

**Issue by dm-gh** [cmc-haskell-2018/straminata#36]
Change 
```haskell
newtype Rectangle = Rectangle (Position, Position)
```
to 
```haskell
type Rectangle = (Position, Position)
```
because we need to unwrap our Rectangle each time we want to get its coordinates, however it is not necessary to wrap it at the first place.

**Comment by alois9866** [comment]
Please, pay attention to the fact that Rectangle type is used throughout the program. Check carefully that the changes does not cause any bugs.
