### ISSUE TITLE
Arithmetical operations on Unwrappable

### ISSUE THREAD

**Issue by alois9866** [cmc-haskell-2018/straminata#51]

**Comment by fizruk** [comment]
There really should not be such a type class in the first place:
- type classes are not Java interfaces, don't use them like that;
- `unwrap` really has nothing to do with `(Float, Float)`.

In general, avoid introducing new type classes unless you absolutely understand what you're doing.
Stick to just plain old functions instead. Don't mind the boilerplate — you'll figure out how to clean that up with other means after a while.

**Comment by alois9866** [comment]
@fizruk This issue name doesn't really mean that we want to add arithmetical operations to `Unwrappable` itself. Please check #52.

**Comment by fizruk** [comment]
@alois9866 yeah that PR introduces another suspicious type class, I see.

`UnwrappablePair` still makes no sense. And `LSE` make little of that.
Basically you can't just use type classes to arbitrarily overload functions — you have to think about what a type class will represent and what laws its instances should abide.

Regarding `LSE` (linear space element) I suggest that you take a look at [`VectorSpace` class](https://hackage.haskell.org/package/vector-space-0.13/docs/Data-VectorSpace.html) defined in a [`vector-space` package](https://hackage.haskell.org/package/vector-space).

However, for you project I highly recommend that you avoid these classes altogether (at least until you have a first working version of the project) and just use simple functions.

**Comment by alois9866** [comment]
@fizruk 
Okay, how you suggest to rewrite `UnwrappablePair`? We only use type classes that way because we don't really want any code duplication _and_ we prefer to keep the `newtype`s to avoid error when we pass parameters to functions. Is there a better way to solve this problems?
