### ISSUE TITLE
Add level representation

### ISSUE THREAD

**Issue by alois9866** [cmc-haskell-2018/straminata#7]
A level should be represented as a file. This file should be loaded at the start of the game somehow.

**Comment by fizruk** [comment]
> A level should be represented as a file

A level should be represented by some data structure.
You can serialise data structures to a file using various methods (JSON/YAML, binary formats, custom text formats, etc.). However the most simple one would be to just use `show` + `writeFile` to save a structure into a file and `read` + `readFile` to read from a file.

**Comment by fizruk** [comment]
Note that you should start with hard-coded level value in your code and then implement ways to save/load levels to/from files.
